/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    1: typeof import('./../views/products/1.vue')['default']
    3: typeof import('./../views/products/3.vue')['default']
    Auth: typeof import('./../views/Auth.vue')['default']
    BackButton: typeof import('./../components/Button/BackButton.vue')['default']
    BackTopButton: typeof import('./../components/Button/BackTopButton.vue')['default']
    BottomButton: typeof import('./../components/Button/BottomButton.vue')['default']
    BottomNav: typeof import('./../layout/BottomNav.vue')['default']
    Cart: typeof import('./../views/cart/Cart.vue')['default']
    Cartlist: typeof import('./../views/cart/Cartlist/Cartlist.vue')['default']
    CateforyList: typeof import('./../views/home/CateforyList.vue')['default']
    Counter: typeof import('./../components/Counter.vue')['default']
    FixedButton: typeof import('./../components/Button/FixedButton.vue')['default']
    FormInput: typeof import('./../components/FormInput.vue')['default']
    Hello: typeof import('./../components/Hello.vue')['default']
    Home: typeof import('./../views/home/Home.vue')['default']
    Layout: typeof import('./../layout/Layout.vue')['default']
    Login: typeof import('./../views/Login.vue')['default']
    Notification: typeof import('./../components/Notificaition/Notification.vue')['default']
    NotificationItem: typeof import('./../components/Notificaition/NotificationItem.vue')['default']
    Product: typeof import('./../views/Product.vue')['default']
    ProductList: typeof import('./../views/products/ProductList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./../views/Search.vue')['default']
    Signup: typeof import('./../views/Signup.vue')['default']
    User: typeof import('./../views/User.vue')['default']
  }
}
