/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
import 'vue'
declare module 'vue' {
  export interface GlobalComponents {
    SvgIcon: import("vue").DefineComponent<{
        name: {
            type: import("vue").PropType<"add" | "back" | "beauty" | "cancel" | "cart" | "chair" | "check" | "close" | "clothes" | "computer" | "eye" | "food" | "home" | "logout" | "noeye" | "outdoor" | "phone" | "remove" | "search" | "toys" | "up" | "user">;
            default: string;
            required: true;
        };
    }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
        name: {
            type: import("vue").PropType<"add" | "back" | "beauty" | "cancel" | "cart" | "chair" | "check" | "close" | "clothes" | "computer" | "eye" | "food" | "home" | "logout" | "noeye" | "outdoor" | "phone" | "remove" | "search" | "toys" | "up" | "user">;
            default: string;
            required: true;
        };
    }>>, {
        name: "add" | "back" | "beauty" | "cancel" | "cart" | "chair" | "check" | "close" | "clothes" | "computer" | "eye" | "food" | "home" | "logout" | "noeye" | "outdoor" | "phone" | "remove" | "search" | "toys" | "up" | "user";
    }>;
  }
}
