/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
declare module '~virtual/svg-component' {
  const SvgIcon: import("vue").DefineComponent<{
      name: {
          type: import("vue").PropType<"add" | "back" | "beauty" | "cancel" | "cart" | "chair" | "check" | "close" | "clothes" | "computer" | "eye" | "food" | "home" | "logout" | "noeye" | "outdoor" | "phone" | "remove" | "search" | "toys" | "up" | "user">;
          default: string;
          required: true;
      };
  }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
      name: {
          type: import("vue").PropType<"add" | "back" | "beauty" | "cancel" | "cart" | "chair" | "check" | "close" | "clothes" | "computer" | "eye" | "food" | "home" | "logout" | "noeye" | "outdoor" | "phone" | "remove" | "search" | "toys" | "up" | "user">;
          default: string;
          required: true;
      };
  }>>, {
      name: "add" | "back" | "beauty" | "cancel" | "cart" | "chair" | "check" | "close" | "clothes" | "computer" | "eye" | "food" | "home" | "logout" | "noeye" | "outdoor" | "phone" | "remove" | "search" | "toys" | "up" | "user";
  }>;
  export const svgNames: ["add", "back", "beauty", "cancel", "cart", "chair", "check", "close", "clothes", "computer", "eye", "food", "home", "logout", "noeye", "outdoor", "phone", "remove", "search", "toys", "up", "user"];
  export type SvgName = "add" | "back" | "beauty" | "cancel" | "cart" | "chair" | "check" | "close" | "clothes" | "computer" | "eye" | "food" | "home" | "logout" | "noeye" | "outdoor" | "phone" | "remove" | "search" | "toys" | "up" | "user";
  export default SvgIcon;
}
